name: flutter_navigation_project
description: A new Flutter project for navigation demo

publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
